export interface Book {
    id: number;
    title: string;
    author: string;
    category: string;
    availability: boolean;
    coverImage: string;
    description?: string;
    isbn?: string;
    publisher?: string;
    year?: string;
    pages?: number;
    language?: string;
}

export const mockBooks: Book[] = [
    {
        id: 1,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        category: "Fiction",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800",
        description: "A classic novel set in the Roaring Twenties, exploring themes of wealth, love, and the American Dream.",
        isbn: "978-0743273565",
        publisher: "Scribner",
        year: "1925",
        pages: 180,
        language: "English"
    },
    {
        id: 2,
        title: "Clean Code",
        author: "Robert C. Martin",
        category: "Technology",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
        description: "A handbook of agile software craftsmanship that teaches how to write better, cleaner code.",
        isbn: "978-0132350884",
        publisher: "Prentice Hall",
        year: "2008",
        pages: 464,
        language: "English"
    },
    {
        id: 3,
        title: "1984",
        author: "George Orwell",
        category: "Fiction",
        availability: false,
        coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800",
        description: "A dystopian social science fiction novel and cautionary tale about totalitarianism and surveillance.",
        isbn: "978-0451524935",
        publisher: "Signet Classic",
        year: "1949",
        pages: 328,
        language: "English"
    },
    {
        id: 4,
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        category: "History",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=800",
        description: "An exploration of the history of Homo sapiens, from the evolution of archaic humans to the present day.",
        isbn: "978-0062316097",
        publisher: "Harper",
        year: "2011",
        pages: 443,
        language: "English"
    },
    {
        id: 5,
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        category: "Science",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=800",
        description: "A landmark volume in science writing by one of the great minds of our time, exploring the universe's origins and fate.",
        isbn: "978-0553380163",
        publisher: "Bantam",
        year: "1988",
        pages: 212,
        language: "English"
    },
    {
        id: 6,
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        category: "Fiction",
        availability: false,
        coverImage: "https://images.unsplash.com/photo-1626618012641-bfbca5a31239?auto=format&fit=crop&q=80&w=800",
        description: "The first novel in the Harry Potter series, following a young wizard as he begins his education at Hogwarts.",
        isbn: "978-0590353427",
        publisher: "Scholastic",
        year: "1997",
        pages: 309,
        language: "English"
    },
    {
        id: 7,
        title: "Rich Dad Poor Dad",
        author: "Robert Kiyosaki",
        category: "Non-Fiction",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?auto=format&fit=crop&q=80&w=800",
        description: "A book that advocates for financial literacy and building wealth through investing and entrepreneurship.",
        isbn: "978-1612680194",
        publisher: "Plata Publishing",
        year: "1997",
        pages: 336,
        language: "English"
    },
    {
        id: 8,
        title: "Steve Jobs",
        author: "Walter Isaacson",
        category: "Biography",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800",
        description: "The exclusive biography of Steve Jobs, based on more than forty interviews with Jobs over two years.",
        isbn: "978-1451648539",
        publisher: "Simon & Schuster",
        year: "2011",
        pages: 656,
        language: "English"
    },
    {
        id: 9,
        title: "Design Patterns",
        author: "Erich Gamma",
        category: "Technology",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=800",
        description: "A foundational text on design patterns, describing common solutions to typical software development challenges.",
        isbn: "978-0201633610",
        publisher: "Addison-Wesley Professional",
        year: "1994",
        pages: 395,
        language: "English"
    },
    {
        id: 101,
        title: "The Midnight Library",
        author: "Matt Haig",
        category: "Fiction",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800",
        description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
        isbn: "978-0525559474",
        publisher: "Viking",
        year: "2020",
        pages: 304,
        language: "English"
    },
    {
        id: 102,
        title: "Atomic Habits",
        author: "James Clear",
        category: "Self-Help",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
        description: "No matter your goals, Atomic Habits offers a proven framework for improving—every day.",
        isbn: "978-0735211292",
        publisher: "Avery",
        year: "2018",
        pages: 320,
        language: "English"
    },
    {
        id: 103,
        title: "Project Hail Mary",
        author: "Andy Weir",
        category: "Sci-Fi",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800",
        description: "A lone astronaut must save the earth from disaster in this propulsive SF thriller from the author of The Martian.",
        isbn: "978-0593135204",
        publisher: "Ballantine Books",
        year: "2021",
        pages: 496,
        language: "English"
    },
    {
        id: 104,
        title: "Klara and the Sun",
        author: "Kazuo Ishiguro",
        category: "Fiction",
        availability: false,
        coverImage: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=800",
        description: "The story of Klara, an Artificial Friend with outstanding observational qualities, who, from her place in the store, watches carefully the behavior of those who come in to browse.",
        isbn: "978-0593318171",
        publisher: "Knopf",
        year: "2021",
        pages: 320,
        language: "English"
    },
    {
        id: 105,
        title: "Think Again",
        author: "Adam Grant",
        category: "Psychology",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=800",
        description: "Discover the critical art of rethinking: learning to question your opinions and open other people's minds.",
        isbn: "978-1984878106",
        publisher: "Viking",
        year: "2021",
        pages: 320,
        language: "English"
    },
    {
        id: 106,
        title: "Malibu Rising",
        author: "Taylor Jenkins Reid",
        category: "Fiction",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1626618012641-bfbca5a31239?auto=format&fit=crop&q=80&w=800",
        description: "Four famous siblings throw an epic party to celebrate the end of the summer. But over the course of twenty-four hours, their lives will change forever.",
        isbn: "978-1524798659",
        publisher: "Ballantine Books",
        year: "2021",
        pages: 384,
        language: "English"
    },
    {
        id: 201,
        title: "Clean Code",
        author: "Robert C. Martin",
        category: "Technology",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
        description: "A handbook of agile software craftsmanship that teaches how to write better, cleaner code.",
        isbn: "978-0132350884",
        publisher: "Prentice Hall",
        year: "2008",
        pages: 464,
        language: "English"
    },
    {
        id: 202,
        title: "The Alchemist",
        author: "Paulo Coelho",
        category: "Fiction",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800",
        description: "A fable about following your dream.",
        isbn: "978-0062315007",
        publisher: "Harper",
        year: "1988",
        pages: 208,
        language: "English"
    },
    {
        id: 203,
        title: "Sapiens",
        author: "Yuval Noah Harari",
        category: "History",
        availability: false,
        coverImage: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=800",
        description: "A brief history of humankind.",
        isbn: "978-0062316097",
        publisher: "Harper",
        year: "2011",
        pages: 443,
        language: "English"
    },
    {
        id: 204,
        title: "The Pragmatic Programmer",
        author: "Andrew Hunt",
        category: "Technology",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800",
        description: "Your journey to mastery.",
        isbn: "978-0135957059",
        publisher: "Addison-Wesley",
        year: "1999",
        pages: 352,
        language: "English"
    },
    {
        id: 205,
        title: "Dune",
        author: "Frank Herbert",
        category: "Sci-Fi",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=800",
        description: "The epic masterpiece of planetary adventure.",
        isbn: "978-0441172719",
        publisher: "Ace",
        year: "1965",
        pages: 412,
        language: "English"
    },
    {
        id: 206,
        title: "The Psychology of Money",
        author: "Morgan Housel",
        category: "Finance",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800",
        description: "Timeless lessons on wealth, greed, and happiness.",
        isbn: "978-0857197689",
        publisher: "Harriman House",
        year: "2020",
        pages: 252,
        language: "English"
    },
    {
        id: 207,
        title: "Deep Work",
        author: "Cal Newport",
        category: "Productivity",
        availability: false,
        coverImage: "https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?auto=format&fit=crop&q=80&w=800",
        description: "Rules for focused success in a distracted world.",
        isbn: "978-1455586691",
        publisher: "Grand Central Publishing",
        year: "2016",
        pages: 304,
        language: "English"
    },
    {
        id: 208,
        title: "Man's Search for Meaning",
        author: "Viktor Frankl",
        category: "Psychology",
        availability: true,
        coverImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=800",
        description: "A psychiatrist's memoir of his survival in Nazi concentration camps.",
        isbn: "978-0807014295",
        publisher: "Beacon Press",
        year: "1946",
        pages: 165,
        language: "English"
    }
];


